config/routes.rb
Rails.application.routes.draw do
  get 'projects/new'
  get 'projects/dashboard'
  post 'projects/create'

  root 'projects#new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name, :description, :state, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  http_basic_authenticate_with name: 'desafiovamoscontodo', password: 'XAHTJEAS23123%23', only: :dashboard
  def new
  end

  def dashboard
    
    if params[:state].present?
      @projects = Project.where('state = ?', params[:state])
    else
      @projects = Project.all
    end
  end

  def create
    @project = Project.create(name: params[:name], description: params[:description], start_date: params[:start_date], 
                              end_date: params[:end_date], state: params[:state])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gestor</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/create.html.erb
<div class="container">
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@project.errors.count, "error") %>
      prohibited this project from being created:
      </h2>
      <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
      <p><%= link_to 'Try again', projects_new_path %></p>
    </div>
  <% else%>
    <h1> Your project was created successfully! </h1>
    <p>Check your recently created project <%= link_to 'here', projects_dashboard_path %></p>
  <% end %>
</div>

app/views/projects/dashboard.html.erb
<div class="container">
  <form class="form-inline">
    <select name="state" id="state">
        <option value="proposal">Proposal</option>
        <option value="in progress">In Progress</option>
        <option value="finished">Finished</option>
      </select>
    <button class="btn btn-success my-2 my-sm-0" type="submit">Search</button>
  </form>
  <p> <%= link_to "Clear filter", projects_dashboard_path %></p>
</div>

<div class="container">
  <h1>Projects</h1>
  <table class="table">
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Start Date</th>
      <th>End Date</th>
      <th>State</th>
    </tr>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.description %></td>
        <td><%= project.start_date %></td>
        <td><%= project.end_date %></td>
        <td><%= project.state %></td>
      </tr>
    <% end %>
  </table>
  <p>Create a new project <%= link_to "here", projects_new_path %>!</p>
</div>

app/views/projects/new.html.erb
<div class="container"><h1> Create a New Project </h1></div>
<div class="container">
    <form method="POST" action="/projects/create" >
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      <div class="form-group">
        <label for="name">Name</label>
        <input name="name" class="form-control" id="name" arial-describedby="nameHelp" placeholder="Enter Project Name">
      </div>

      <div class="form-group">
        <label for="description">Description</label>
        <textarea name="description" type="text" class="form-control"></textarea>
      </div>

      <div class="form-group">
        <label for="start_date">Start Date</label>
        <input name="start_date" class="form-control" type="date">
      </div>

      <div class="form-group">
        <label for="end_date">End Date</label>
        <input name="end_date" class="form-control" type="date">
      </div>

      <div class="form-group">
        <label for="state">State</label>
        <select name="state" id="state">
          <option value="proposal">Proposal</option>
          <option value="in progress">In Progress</option>
          <option value="finished">Finished</option>
        </select>
      </div>

      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    <br>
    <p>Check all projects <%= link_to "here", projects_dashboard_path %>!</p>
</div>